[package]
name = "inputcodex-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
inputcodex-application.workspace = true
inputcodex-domain.workspace = true
serde_json.workspace = true
toml_edit.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows.workspace = true
windows-registry.workspace = true

[lints]
workspace = true
